import = ["~/.config/alacritty/rose-pine.toml"]

[window]
padding = { x = 4, y = 4}
decorations = "None"
opacity = 0.825

[font]
normal = { family = "0xProto", style = "Mono"}
size = 12
builtin_box_drawing = true

[cursor]
style = { shape = "Block", blinking = "On" }

