gui:
  theme:
    selectedLineBgColor:
      - black
    inactiveBorderColor:
      - "#6e6a86"
  nerdFontsVersion: "3"
  statusPanelView: allBranchesLog
  spinner:
    frames:
    - "⣼"
    - "⣹"
    - "⢻"
    - "⠿"
    - "⡟"
    - "⣏"
    - "⣧"
    - "⣶"

git:
  paging:
    colorArg: always
    pager: "delta --dark --paging=never --line-numbers --hyperlinks"
