background          = 0xFF000000
base                = 0xFF000000
alternate_base      = 0xFF191724
text                = 0xFFE0DEF4
accent              = 0xFF31748F
accent_secondary    = 0xFFEBBCBA
bright_text         = 0xFFE0DEF4
font_family         = "ZxGamut"
